### ISSUE TITLE
[Question] Does DSL work with this built?

### ISSUE THREAD

**Issue by n00bundercover** [gt945/Netgear-D7800-Openwrt#2]
Sorry for asking this question via github issue, just could not think of a better way.

Does dsl connection work with this? The D7800 is not very well documented on openwrt pages, but they all say dsl is not working. I stumbled over your source, and there is at least some files for the VR10 modem...

So does that mean dsl should work with your version? That would be really awesome!

**Comment by gt945** [comment]
This repo is openwrt source code from Netgear. It seems include some prebuilt driver for dsl, but I never tested it.

**Comment by n00bundercover** [comment]
Thanks for the answer! I'll try to get my hands on this device and test it.

**Comment by DahilerMehvOlur** [comment]
> Thanks for the answer! I'll try to get my hands on this device and test it.

So what happen? Did it work?
